# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

env:
  global:
    # wait for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)
    - TARGET_API=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ABI=armeabi-v7a
    - ABI_TAG=google_apis

os:
  - linux

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$TARGET_API
    # For Google APIs
    - addon-google_apis-google-$TARGET_API
    # Google Play Services
#    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-$ABI-$ABI_TAG-$TARGET_API

script:
  - ./wait_for_emulator
  - ./gradlew clean check connectedCheck
 
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t "android-"$TARGET_API --abi $ABI --tag $ABI_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
notifications:
  email: true
 
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/