# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10

os:
  - linux

android:
  components:
    - platform-tools
    - tools
    - android-25
    - android-23
    - android-21
    - android-19
    - android-14
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
#    - extra-google-google_play_services
#    - extra-google-admob_ads_sdk
#    - extra-google-gcm
    - sys-img-armeabi-v7a-android-25
    - sys-img-x86-android-25

before_install:
  - chmod +x gradlew
  
script:
  - ./gradlew build connectedCheck
 
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
notifications:
  email: true
 
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle